import random
dice_number = random.randint(1, 6)
if dice_number == 1:
    print(f"****************")
    print(f"**            **")
    print(f"**            **")
    print(f"**    ****    **")
    print(f"**            **")
    print(f"**            **")
    print(f"****************")
elif dice_number == 2:
    print(f"****************")
    print(f"**            **")
    print(f"**    ****    **")
    print(f"**            **")
    print(f"**    ****    **")
    print(f"**            **")
    print(f"****************")
elif dice_number == 3:
    print(f"****************")
    print(f"**            **")
    print(f"**    ****    **")
    print(f"**    ****    **")
    print(f"**    ****    **")
    print(f"**            **")
    print(f"****************")
elif dice_number == 4:
    print(f"****************")
    print(f"**            **")
    print(f"**   **  **   **")
    print(f"**            **")
    print(f"**   **  **   **")
    print(f"**            **")
    print(f"****************")
elif dice_number == 5:
    print(f"****************")
    print(f"**            **")
    print(f"**   **  **   **")
    print(f"**     **     **")
    print(f"**   **  **   **")
    print(f"**            **")
    print(f"****************")
elif dice_number == 6:
    print(f"****************")
    print(f"**            **")
    print(f"**   **  **   **")
    print(f"**   **  **   **")
    print(f"**   **  **   **")
    print(f"**            **")
    print(f"****************")